/**
 * Backfills `photoUrl` on `directors` from TMDB, keyed by sourceId (the TMDB
 * person id). Photos are language-agnostic, so this lives here as a one-off ops
 * tool. Biographies are NOT handled here - they must be Polish, generated by
 * the scraper via Gemini (see filmweb-data-scrapper). Re-runnable: only fills
 * directors still missing a photo.
 *
 * Auth (set one in .env):
 *   TMDB_READ_TOKEN  - v4 read access token (sent as Bearer), preferred
 *   TMDB_API_KEY     - v3 API key (sent as ?api_key=)
 *
 * Usage: bunx ts-node -r dotenv/config src/scripts/backfill-director-photos.ts
 */
import 'dotenv/config';
import { Client, type QueryResultRow } from 'pg';

const IMAGE_BASE = 'https://image.tmdb.org/t/p/w500';
const TMDB_BASE = 'https://api.themoviedb.org/3';
const CONCURRENCY = 8;

const readToken = process.env.TMDB_READ_TOKEN;
const apiKey = process.env.TMDB_API_KEY;

type TmdbPerson = { profile_path: string | null };

const fetchPhotoUrl = async (sourceId: number): Promise<string | null> => {
  const params = new URLSearchParams();
  if (!readToken && apiKey) params.set('api_key', apiKey);
  const url = `${TMDB_BASE}/person/${sourceId}?${params.toString()}`;

  const res = await fetch(url, {
    headers: readToken ? { Authorization: `Bearer ${readToken}` } : {},
  });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`TMDB ${res.status} for person ${sourceId}`);

  const person = (await res.json()) as TmdbPerson;
  return person.profile_path ? `${IMAGE_BASE}${person.profile_path}` : null;
};

const run = async () => {
  if (!readToken && !apiKey) {
    throw new Error(
      'Set TMDB_READ_TOKEN (v4 bearer) or TMDB_API_KEY (v3) in .env',
    );
  }

  const client = new Client(process.env.DATABASE_URL);
  await client.connect();

  try {
    const { rows } = await client.query<QueryResultRow>(
      `SELECT id, "sourceId" FROM directors WHERE "photoUrl" IS NULL ORDER BY id`,
    );

    if (rows.length === 0) {
      console.log('directors: nothing to backfill');
      return;
    }

    console.log(`directors: fetching TMDB photos for ${rows.length} row(s)...`);

    let updated = 0;
    let skipped = 0;
    let failed = 0;

    for (let i = 0; i < rows.length; i += CONCURRENCY) {
      const batch = rows.slice(i, i + CONCURRENCY);
      await Promise.all(
        batch.map(async (row) => {
          try {
            const photoUrl = await fetchPhotoUrl(row.sourceId as number);
            if (!photoUrl) {
              skipped++;
              return;
            }
            await client.query(
              `UPDATE directors SET "photoUrl" = $1, "updatedAt" = now() WHERE id = $2`,
              [photoUrl, row.id],
            );
            updated++;
          } catch (err) {
            failed++;
            console.warn(
              `  person ${row.sourceId} failed: ${err instanceof Error ? err.message : String(err)}`,
            );
          }
        }),
      );
      console.log(
        `  processed ${Math.min(i + CONCURRENCY, rows.length)}/${rows.length}`,
      );
    }

    console.log(
      `directors: ${updated} updated, ${skipped} without a TMDB photo, ${failed} failed`,
    );
  } finally {
    await client.end();
  }
};

run().catch((err) => {
  console.error('Photo backfill failed:', err);
  process.exit(1);
});
